server:
  port: ${PORT:8082}

spring:
  application:
    name: user-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-calm-wind-aht693c7-pooler.c-3.us-east-1.aws.neon.tech/users_service_db}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_GFRUAMs1n0pz}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

services:
  auth:
    base-url: ${AUTH_SERVICE_URL:https://auth-service}

security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY:key123}
    user:
      generator: ${JWT_USER_GENERATOR:ProScience}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    tryItOutEnabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
